# Generated by Django 5.0.6 on ... (Date will vary)
# -*- coding: utf-8 -*-
# Generated by Django 5.0.6 on 2024-05-06 15:00 # <--- Your date might differ
from django.db import migrations, models
import uuid # <--- Make sure uuid is imported


# --- Function to Generate UUIDs ---
def gen_uuid(apps, schema_editor):
    ResumeSuggestion = apps.get_model('resumes', 'ResumeSuggestion')
    # Important: We iterate over the model *before* the old ID is removed
    # and *after* the temp_uuid field is added by the operations list below.
    for row in ResumeSuggestion.objects.all():
        row.temp_uuid = uuid.uuid4()
        row.save(update_fields=['temp_uuid'])
# --- End of Function ---


class Migration(migrations.Migration):

    dependencies = [
        # Add the previous migration file name here, e.g.:
        ('resumes', '0002_initial'), # <-- Adjust if your previous migration has a different name
    ]

    operations = [
        # 1. Add the 'status' field
        migrations.AddField(
            model_name='resumesuggestion',
            name='status',
            field=models.CharField(default='pending', max_length=20),
            # preserve_default=False, # Usually not needed unless default changes later
        ),
        # 2. Alter 'suggestion_data' to add default=dict
        migrations.AlterField(
            model_name='resumesuggestion',
            name='suggestion_data',
            field=models.JSONField(default=dict),
        ),

        # --- Safely Change 'id' from AutoField/BigInt to UUID ---

        # 3. Add a *temporary* UUID field (nullable for now)
        migrations.AddField(
            model_name='resumesuggestion',
            name='temp_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True), # Must be nullable initially
        ),

        # 4. Run the Python function to populate the temporary UUID field for existing rows
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop), # Added reverse_code

        # 5. Make the temporary UUID field non-nullable and unique
        #    (Ensures all rows got a UUID before removing the old PK)
        #    Making it unique *before* making it PK avoids potential issues in some DBs
        migrations.AlterField(
            model_name='resumesuggestion',
            name='temp_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True), # Add unique=True
             # We set null=False implicitly by not specifying null=True anymore AFTER RunPython
        ),

        # 6. Remove the original 'id' (AutoField/BigIntegerField) column
        migrations.RemoveField(
            model_name='resumesuggestion',
            name='id',
        ),

        # 7. Rename the temporary UUID field to 'id'
        migrations.RenameField(
            model_name='resumesuggestion',
            old_name='temp_uuid',
            new_name='id',
        ),

        # 8. Alter the 'id' field (which is now the UUID field) to make it the primary key
        #    Ensure serialize=False is set for Primary Keys.
        migrations.AlterField(
            model_name='resumesuggestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        # --- End: Safe Change for 'id' ---
    ]